import { describe, expect, test } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { quoteBluedart } from './bluedart';
import { BLUEDART_DEFAULT_DATA, type BluedartService } from '../domain/bluedart';

/**
 * The Bluedart engine against the workbook's own Calculator.
 *
 * 127 cases, generated by driving `DNS_Directional_RateCard_Calculator.xlsx` through
 * headless LibreOffice (`scripts/generate_franchise_fixtures.py`). The workbook ships with
 * no cached values, so these numbers did not exist until that recalculation produced them.
 *
 * Compared with `toBe`, not `toBeCloseTo`. The workbook rounds nothing — its GST on a 30 kg
 * surface shipment is ₹177.9975 — and so neither does the engine. Anything approximate here
 * would hide exactly the kind of error this suite exists to catch.
 *
 * Two divergences are deliberate and asserted separately at the bottom.
 */

interface Fixture {
  case: {
    id: string;
    description: string;
    pincode: number;
    weight: number;
    service: string;
    declaredValue: number;
    fuelAir: number;
    fuelSurface: number;
  };
  expected: {
    zone: string;
    odaStatus: string | null;
    edlKm: number;
    chargeableWeight: number;
    freight: number;
    oda: number;
    fuel: number;
    awb: number;
    fov: number;
    subTotal: number;
    gst: number;
    total: number;
  };
}

const fixtures: { cases: Fixture[] } = JSON.parse(
  readFileSync(join(import.meta.dirname, '__fixtures__', 'franchise-golden.json'), 'utf8'),
);

/** The workbook's fuel percentages are inputs, so each case carries its own. */
const dataFor = (fuelAir: number, fuelSurface: number) => ({
  ...BLUEDART_DEFAULT_DATA,
  charges: { ...BLUEDART_DEFAULT_DATA.charges, fuelAir, fuelSurface },
});

/**
 * Cases the engine deliberately answers differently from the workbook, each with its
 * reason. Everything else must match to the last decimal place.
 */
const DELIBERATE_DIVERGENCE: Record<string, string> = {
  // The workbook prices an unknown pincode at zero freight and still bills AWB, FOV and
  // GST — ₹354 for a shipment it cannot route. The engine refuses to quote.
  'unknown-pincode': 'refuses rather than billing ₹354 for a pincode it cannot route',
  // 15 pincodes are marked not APEX-serviceable; the workbook quotes them anyway.
  'apex-not-in-apex': 'refuses APEX where the master says it is not served',
};

const priceable = fixtures.cases.filter((f) => !(f.case.id in DELIBERATE_DIVERGENCE));

describe('the Bluedart card reproduces the workbook exactly', () => {
  test('the fixture set covers every service and zone', () => {
    const services = new Set(fixtures.cases.map((f) => f.case.service));
    expect([...services].sort()).toEqual(['APEX', 'DOCs', 'DUTS', 'SURFACE']);
    const zones = new Set(fixtures.cases.map((f) => f.expected.zone));
    for (const zone of ['WEST', 'NORTH', 'SOUTH', 'EAST', 'NE & REMOTE']) {
      expect(zones).toContain(zone);
    }
    expect(fixtures.cases.length).toBe(127);
  });

  for (const fixture of priceable) {
    const { case: input, expected } = fixture;

    test(`${input.id} — ${input.description}`, () => {
      const result = quoteBluedart(
        {
          service: input.service as BluedartService,
          actualWeight: input.weight,
          declaredValue: input.declaredValue,
        },
        {
          zone: expected.zone,
          odaStatus: expected.odaStatus ?? '',
          edlKm: expected.edlKm,
        },
        dataFor(input.fuelAir, input.fuelSurface),
      );

      if (!result.available) throw new Error(`expected a price: ${result.message}`);
      const b = result.breakdown;

      expect(b.chargeableWeight).toBe(expected.chargeableWeight);
      expect(b.freight).toBe(expected.freight);
      expect(b.oda).toBe(expected.oda);
      expect(b.fuel).toBe(expected.fuel);
      expect(b.awb).toBe(expected.awb);
      expect(b.fov).toBe(expected.fov);
      expect(b.subTotal).toBe(expected.subTotal);
      expect(b.gst).toBe(expected.gst);
      expect(b.total).toBe(expected.total);
    });
  }
});

describe('where the engine deliberately differs from the workbook', () => {
  const fixtureFor = (id: string) => fixtures.cases.find((f) => f.case.id === id);

  test('an unknown pincode is refused, not billed ₹354 of charges on nil freight', () => {
    const fixture = fixtureFor('unknown-pincode');
    // What the workbook does: no zone, no freight, and a bill anyway.
    expect(fixture?.expected.zone).toBe('PIN NOT FOUND');
    expect(fixture?.expected.freight).toBe(0);
    expect(fixture?.expected.total).toBe(354);

    const result = quoteBluedart(
      { service: 'SURFACE', actualWeight: 30 },
      null,
      BLUEDART_DEFAULT_DATA,
    );
    expect(result.available).toBe(false);
    if (result.available) return;
    expect(result.reason).toBe('unknown-pincode');
  });

  test('APEX is refused where the master says it is not served', () => {
    const fixture = fixtureFor('apex-not-in-apex');
    expect(fixture?.expected.odaStatus).toBe('Not in APEX');
    // The workbook quotes it regardless.
    expect(fixture?.expected.total).toBeGreaterThan(0);

    const result = quoteBluedart(
      { service: 'APEX', actualWeight: 30 },
      { zone: fixture?.expected.zone ?? 'WEST', odaStatus: 'Not in APEX', edlKm: 0 },
      BLUEDART_DEFAULT_DATA,
    );
    expect(result.available).toBe(false);
    if (result.available) return;
    expect(result.reason).toBe('apex-not-serviceable');
    expect(result.message).toMatch(/surface/i);
  });

  test('the same pincode still prices on SURFACE', () => {
    const fixture = fixtureFor('apex-not-in-apex');
    const result = quoteBluedart(
      { service: 'SURFACE', actualWeight: 30, declaredValue: 5000 },
      { zone: fixture?.expected.zone ?? 'WEST', odaStatus: 'Not in APEX', edlKm: 0 },
      BLUEDART_DEFAULT_DATA,
    );
    expect(result.available).toBe(true);
  });
});
