import { describe, expect, test } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { quote } from './quote';
import type { Mode, Pincode, RateCard } from '../domain/types';

/**
 * The definitive verification: every case is priced by the engine and compared to
 * what the source workbook itself computed for the same inputs.
 *
 * Fixtures are generated by scripts/generate_fixtures.py, which drives each
 * workbook's own Rate Calculator through LibreOffice. If this suite passes, the
 * engine reproduces the spreadsheets to the rupee.
 */

const root = join(import.meta.dirname, '..', '..');

interface Fixture {
  models: {
    key: string;
    freightMethod: string;
    cases: {
      case: {
        id: string;
        description: string;
        mode: string;
        fromPincode: number;
        toPincode: number;
        actualWeight: number;
        length: number;
        breadth: number;
        height: number;
        pieces: number;
        singlePackageOver100kg: boolean;
      };
      expected: Record<string, unknown>;
    }[];
  }[];
}

const fixtures: Fixture = JSON.parse(
  readFileSync(join(import.meta.dirname, '__fixtures__', 'golden.json'), 'utf8'),
);

const pincodeList: Pincode[] = JSON.parse(
  readFileSync(join(root, 'data', 'extracted', 'pincodes.json'), 'utf8'),
);
const pincodes = new Map(pincodeList.map((p) => [p.pincode, p]));

const cards = new Map(
  ['model-1', 'model-2', 'model-3'].map((key) => [
    key,
    JSON.parse(readFileSync(join(root, 'data', 'extracted', `${key}.json`), 'utf8')) as RateCard,
  ]),
);

/** Excel writes an em dash or an explanatory sentence where there is no number. */
const isNumeric = (value: unknown): value is number => typeof value === 'number';

for (const model of fixtures.models) {
  const card = cards.get(model.key);
  if (!card) throw new Error(`no extracted card for ${model.key}`);

  describe(`${model.key} (${model.freightMethod}) reproduces the workbook`, () => {
    for (const { case: c, expected } of model.cases) {
      test(`${c.id} — ${c.description}`, () => {
        const result = quote(
          {
            mode: c.mode.toLowerCase() as Mode,
            actualWeight: c.actualWeight,
            length: c.length,
            breadth: c.breadth,
            height: c.height,
            pieces: c.pieces,
            singlePackageOver100kg: c.singlePackageOver100kg,
          },
          {
            origin: pincodes.get(c.fromPincode) ?? null,
            destination: pincodes.get(c.toPincode) ?? null,
          },
          card,
        );

        // Where the workbook could not produce a freight number, the engine must
        // decline rather than invent one.
        if (!isNumeric(expected.freight)) {
          expect(result.available).toBe(false);
          return;
        }

        if (!result.available) {
          throw new Error(`engine declined a lane the workbook priced: ${result.reason}`);
        }
        const b = result.breakdown;

        expect(b.originZone).toBe(expected.originZone);
        expect(b.destinationZone).toBe(expected.destZone);
        expect(b.originEdlKm).toBe(expected.originEdlKm);
        expect(b.destinationEdlKm).toBe(expected.destEdlKm);
        expect(b.volumetricWeight).toBe(expected.volumetricWeight);
        expect(b.chargeableWeight).toBe(expected.chargeableWeight);

        expect(b.rates.minCharge).toBe(expected.minCharge);
        if (isNumeric(expected.tier1Rate)) expect(b.rates.tier1).toBe(expected.tier1Rate);
        if (isNumeric(expected.tier2Rate)) expect(b.rates.tier2).toBe(expected.tier2Rate);
        if (isNumeric(expected.tier3Rate)) expect(b.rates.tier3).toBe(expected.tier3Rate);

        expect(b.freight).toBe(expected.freight);
        expect(b.pickup).toBe(expected.pickup);
        expect(b.pickupOda).toBe(expected.pickupOda);
        expect(b.delivery).toBe(expected.delivery);
        expect(b.deliveryOda).toBe(expected.deliveryOda);
        expect(b.fuel).toBe(expected.fuel);
        expect(b.docket).toBe(expected.docket);
        expect(b.subTotal).toBe(expected.subTotal);
        expect(b.gst).toBe(expected.gst);
        expect(b.total).toBe(expected.total);

        // NFO transit is a fixed "10-14 hrs" label in the workbook rather than a
        // day count, so only day-based modes are compared here.
        if (isNumeric(expected.transitTime)) {
          expect(b.transitDays).toBe(expected.transitTime);
        }
      });
    }
  });
}
